apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skillsmapper
build:
  artifacts:
  - image: gcr.io/codetaming-skillsmapper/skillsmapperd
deploy:
  kubectl:
    manifests:
    - k8s/test.yaml
