apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: skillsmapper
build:
  artifacts:
  - image: gcr.io/codetaming-skillsmapper/skillsmapperd
    custom:
      buildCommand: ./build.sh
deploy:
  kubectl:
    manifests:
    - k8s/skillsmapper.yaml
