name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.RUN_PROJECT }}
      RUN_REGION: ${{ secrets.RUN_REGION }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: $PROJECT_ID

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --quiet \
            --region $RUN_REGION \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated